"""empty message

Revision ID: 92444046746c
Revises: d56e673cefc2
Create Date: 2019-12-10 21:50:20.276797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92444046746c'
down_revision = 'd56e673cefc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('image', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'image')
    # ### end Alembic commands ###
