"""update Category table

Revision ID: f120c80a943f
Revises: 4f50604856ba
Create Date: 2020-02-18 16:42:50.727162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f120c80a943f'
down_revision = '4f50604856ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_name'), table_name='category')
    # ### end Alembic commands ###
